export const SESSION_ADMIN_LOGIN = "JOBS_AU_ADMIN_LOGIN"
export const SESSION_ADMIN_USER = "JOBS_AU_ADMIN_USER"
export const SESSION_ADMIN_ID = "JOBS_AU_ADMIN_ID"
export const SESSION_ADMIN_TYPE = "JOBS_AU_ADMIN_TYPE"